### ISSUE TITLE
flake8 compliance

### ISSUE THREAD

**Issue by chiradeep** [citrix/netscaler-ansible-modules#2]
At least the E, W and Q class of errors.
Also, fix or remove TODO

**Comment by giorgos-nikolopoulos** [comment]
@chiradeep 

This issue is resolved mainly with the following commits
* c9db59ca6beef28386a8787bb6834ce744a6d4eb
* 9b2109a1bfafac6ccfebfcc192fbcb5e37623f84
* 219555524f724584f0eee69684e298d12896673e
* e28533f15c3459606e652e1c0485891603c1de39
* 510c58006dc9c6f0f7ffab7c12bce786737377d7
* 9d6bd98b5278702456122499383dd3b897509cb8
* c5816c45bd36d2062f90b91a420538b8939d0655
* 7e91a86193c278a921f99510df3f9d8f5c79f56f
* d0903b13940b84ba6433cab5a537e70486c536e5
* cad8941bc443f6aa8935baf70a5f8fbb1dd8eb22

There are some additional commits that fix some issues with the ansible documentation generation tool.

Note that the actual flake8 parameters used can be found int lint.sh script of the repo.

In this file we explicitely ignore E402 which is the ' import must be at the top' rule and the maximum line width is set to 160 characters long.

Both are suggestions taken from the ansible guidelines.

The only remaining flake8 errors I get is about the unused log functions in some modules which when we tidy up the logging in each module should be fixed.

**Comment by chiradeep** [comment]
After a successful merge with mainline Ansible, this means that this code meets Ansible code format guidelines.
