### ISSUE TITLE
netscaler_servicegroup overides members in SG

### ISSUE THREAD

**Issue by eliran143** [citrix/netscaler-ansible-modules#3]
when using netscaler_servicegroup with present operation the module remove exist member and adding only members from the list.

    - name: Set Test-sg
      local_action:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        ssl_cert_validation: "{{ ssl_cert_validation }}"
        nitro_protocol: "{{ nitro_protocol }}"

        module: netscaler_servicegroup
        operation: present

        servicegroupname: Test-sg
        servicetype: HTTP
        servicemembers:
            - ip: "{{ item }}"
              port: 8080
              weight: 50
      with_items: "{{ groups['tomcat'] }}"

The result is there's a single member in the SG instead the entire group

**Comment by eliran143** [comment]
Temporary solution if anyone need

    - name: Prepare service members list for SG
      set_fact:
        servicemembers: "{{servicemembers|default([]) + [{'ip': item , 'port': 389, 'weight': 50}] }}"
      with_items: "{{ groups['ldap'] }}"

    - name: Set LDAP service group
      local_action:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        ssl_cert_validation: "{{ ssl_cert_validation }}"
        nitro_protocol: "{{ nitro_protocol }}"

        module: netscaler_servicegroup
        operation: present

        servicegroupname: ldap-sg
        servicetype: SSL
        servicemembers: "{{ servicemembers }}"

**Comment by giorgos-nikolopoulos** [comment]
This is the expected behavior.

The module parses the configuration from the play book and tries to enforce this particular state.

It does not define operations such as "add service member" or "delete service member".

I think this is more in accordance with Ansible's guidelines for the modules to be declarative rather than imperative.

Do you have knowledge of any specific Ansible module that handles this situation differently?

Perhaps we could implement such a solution in our module too.

Apart from that using Ansible constructs, like the one you have shared, to accomplish such tasks is the way to go.

**Comment by eliran143** [comment]
I think that present should verify that service member exist in the service group, if the member exist the status of the task is ok. 
If the service member is not inside the service group then the task should add it.

the solution above is good when you add the netscaler task as a play, but if i want to use it as a task inside a deployment play it become more complex.

i think most of the modules using present as a state that the package\file\whatever exist 
yum module behave that way.
