### ISSUE TITLE
Enabled features always reports changed, even when not changed

### ISSUE THREAD

**Issue by mikeycmccarthy** [citrix/netscaler-ansible-modules#42]
Running the netscaler_nitro_request to enable features, just like the example in the code, reports changed each and every time, despite not changing anything. Not sure if this is expected behaviour given what the API returns?

Tested with Ansible 2.5.0rc1, installed via pip, on OSX

**Comment by giorgos-nikolopoulos** [comment]
This is the expected behavior.

Since this is a low level module I opted to keep it simple for robustness reasons.
As such there is no check for the value changing and the changed status is always set to true.

If you want to see if a value change will happen you can construct a more complex playbook that will first retrieve the value and then make the change if necessary.

A playbook that has this kind of logic can be found in [this sample](https://github.com/citrix/netscaler-ansible-modules/blob/master/samples/nitro_request/add_or_update_server.yaml).

**Comment by mikeycmccarthy** [comment]
Makes sense, many thanks.
