### ISSUE TITLE
Generic cli module for show commands?

### ISSUE THREAD

**Issue by mattincarlsbad** [citrix/netscaler-ansible-modules#50]
It would be very helpful for my team if we had a generic ansible cli module to use for show commands, scp of new code, and Unix bash commands (shell ls /nsconfig/ssl for example).  We're using nitro right now, but the development cycle for new features/functions is much longer for us than for typical ansible playbooks.  We have ~120 netscalers deployed, so this would save us significant time.

Something similar to the eos_command module would be great:

http://docs.ansible.com/ansible/latest/modules/eos_command_module.html#eos-command-module

We use the heck out of this one.

**Comment by giorgos-nikolopoulos** [comment]
@mattincarlsbad 

We have recently added the `citrix_adc_connection` plugin that allows to execute any Ansible module on the target Citrix ADC.

Running an arbitrary nscli command can be accomplished with the use of the standard Ansible module `shell`.

An example is provided [here](https://github.com/citrix/netscaler-ansible-modules/blob/master/samples/citrix_adc_connection_plugin/nscli_command.yaml)

Refer to the connection plugin README [section](https://github.com/citrix/netscaler-ansible-modules#citrix-adc-connection-plugin) for instructions on how to set it up and get it working.

This [directory](https://github.com/citrix/netscaler-ansible-modules/tree/master/samples/citrix_adc_connection_plugin) contains further examples on the connection plugin.

I will be closing this issue. If you find any problems please re open an issue referring to this one so that we can pickup the trail.
