### ISSUE TITLE
responderpolicy and responderaction already in use

### ISSUE THREAD

**Issue by smilhomme** [citrix/netscaler-ansible-modules#57]
Hi,

Adding responderpolicy and responderaction for the first time works great. 
However, running same playbook a second time returns errors on the responder elements saying it is already in use.

"msg": "NITRO Failure", 
"nitro_errorcode": 3094, 
"nitro_message": "Policy name already in use [by a responder policy]",
"nitro_severity": "ERROR"}

The behavior should be the same as servers, services, lbvservers, etc
status should be :
  ok if already there and unchanged
  changed if added or changed
  failed if anything else goes wrong

Am I wrong? Does it make sense? Thanks in advance.

**Comment by giorgos-nikolopoulos** [comment]
You don't mention the module you are using but form the response data i'm guessing it is `netascaler_nitro_request`.

This module is low level and does not do the checks the rest of the modules do.
You probably try to add the same resource twice which and get a nitro error which is the expected behavior.

Have a look at [this example](https://github.com/citrix/netscaler-ansible-modules/blob/master/samples/nitro_request/add_or_update_server.yaml) to see how you could write a playbook that first checks the existence of a resource and then applies the appropriate action.

**Comment by smilhomme** [comment]
Hi,
You're right. I'm using specific modules to configure (add,update,etc) the server, service, lbvserver, etc.
But I'm using the nitro_request to put in responder policy and action because there is no modules for it.

Thanks for pointing that out, I will go around the issue by using two steps from the example.

Thanks again!
Simon
