### ISSUE TITLE
Use new httpapi connection method

### ISSUE THREAD

**Issue by LukeDRussell** [citrix/netscaler-ansible-modules#63]
Hi,

It would be nice to see the netscaler modules included with Ansible updated to use the [httpapi](https://docs.ansible.com/ansible/devel/plugins/connection/httpapi.html) connection method.

This would save the need to use `delegate_to` or to use the `provider` style credentials. You could then use all the normal ansible methods of providing authentication.

**Comment by giorgos-nikolopoulos** [comment]
From what I can see the httpapi connection plugin is currently implemented for eos and nxos modules.

In these modules there is a one to one correspondence of cli commands and http requests.
This is implemented in each device as an HTTP API that is quite specific for this job. That is accept POST requests with cli commands encoded inside and provide the output of these commands' execution in the HTTP response.

Also in these modules (eos_*, nxos_* ) all configuration is translated to a cli command sequence that will perform the desired configuration changes.

In the case of Netscaler there is no such correspondence. The NITRO API is not a one to one translation of nscli commands to HTTP requests. It is instead a REST API that exposes the configuration objects that are defined in the core of the Citrix ADC software. In other words it invokes the same configuration system that nscli also invokes but presents it in a different manner than the nscli does.

Therefore it is not feasible to implement an httpapi connection plugin because the NITRO API is not suitable for this kind of configuration.
