### ISSUE TITLE
List of modules is blank in web broswer

### ISSUE THREAD

**Issue by ActualReverend** [citrix/netscaler-ansible-modules#86]
When visiting https://netscaler-ansible.readthedocs.io/en/latest/modules/list_of_network_modules.html#netscaler  there is not a list of modules.  When I look at the github entry (https://github.com/citrix/netscaler-ansible-modules/blob/master/docs/modules/list_of_network_modules.rst) it looks like something should be displayed.

**Comment by giorgos-nikolopoulos** [comment]
Yes it's a known issue.

For publishing the modules we are using code from the Ansible source tree used to produce the Ansible documentation site.

More specifically we are using the [plugin_formatter.py](https://github.com/ansible/ansible/blob/devel/docs/bin/plugin_formatter.py) script.

Since this script is run as part of a larger framework some modifications are needed to make it run properly standalone as we do.

Side effect of this is that categorization of modules does not work exactly as expected which results in the network modules' page not containing correct information.

You can still find the list of the netscaler modules under the [all modules](https://netscaler-ansible.readthedocs.io/en/latest/modules/list_of_all_modules.html) category.
